name: project-euler
version: 0.1.0.0
github: "githubuser/project-euler"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/project-euler#readme>

dependencies:
  - base >= 4.7 && < 5
  - extra
  - formatting
  - template-haskell
  - wreq
  - bytestring
  - lens
  - timeit
  - primes
  - grid

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: lib

executables:
  project-euler-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -Wall
      - -Wextra
    dependencies:
      - project-euler

tests:
  project-euler-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - project-euler
